### PR TITLE
Fix the bug that prevent user to login or register to the site

### PR DESCRIPTION
**Pull request by ChristianGiupponi**
This fix is about this issue: https://github.com/AsgardCms/Platform/issues/581

In short the default `route` method do not consider the middleware about the localization so the action in the form are incorrect.  
For example for the login the url is just `auth/login` but the post method responds to `en/auth/login` so the route is never called.  

With this fix I have added a new helper function called `localize_route` that get the current url and add the current localization to create the correct url.  
I think that this is a general problem and in the blade views we should use always this function.

Hope this work for all of you, there is no frontend tests so I can't add tests for this commit, please try and let me know.

### CODE REVIEW

**Comment by nWidart** [comment]
Hi and thank you for the fix!

I just checked out the branch and I'm getting the following error:

```
Argument 2 passed to Symfony\Component\HttpFoundation\Request::setTrustedProxies() must be of the type integer, array given, called in /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php on line 54
```


I'm wondering what introduced this issue 🤔 .
Could it be possible to still use the `Form::` helper by using the action option:

```
{!! Form::open(['action' => localize_route('login.post')]) !!}
```

**Comment by ChristianGiupponi** [comment]
That's wired, I'm not getting any error. No problem, I will send a new request using Form helper, just give me a second

**Comment by nWidart** [comment]
Oh I see, it's because I was coming from the master branch which is on laravel 5.6 😄 I've downgraded back to 5.5.

**Comment by ChristianGiupponi** [comment]
Ok, so no need to change? Or still better using the Form helper?

**Comment by nWidart** [comment]
I'm not sure. This indeed fixes it, but there are still a bunch of routes broken. Example: the setting page.

It might be better to find the underlying issue.

**Comment by ChristianGiupponi** [comment]
The wired thing is that I have another project running asgardcms and I have no issue on it.  
I have noticed that with a new project as soon as you run `composer install` it download old version of the modules that do not match the current code on this repo. Maybe is this the issue?  
For example with a new installation I do not have my old fix about the page module

**Comment by motchju** [comment]
well I upgrated from 3.5.3 to 3.6 and I have the issue

**Comment by nWidart** [comment]
I suspect it might be something related to the route cache pull request (https://github.com/AsgardCms/Platform/commit/a86e26883e2605c439975aa616a9d67d074b76eb#diff-0a94741f72a5a3bb035a04974c7e6858) but not sure at the moment.

**Comment by nWidart** [comment]
I've pushed the revert on 3.0 branch. If someone can validate I can tag a patch release.

**Comment by motchju** [comment]
working for me

**Comment by motchju** [comment]
mmm I 've got other issue, will check later, can do it for the moment (I don't have my laptop)

**Comment by nWidart** [comment]
I'm in a meeting now and the afternoon, I'll keep on eye on your issue.

**Comment by motchju** [comment]
talk to soon , the online version was not up-to-date, so for me this fix is correct !

**Comment by daoanhvuacc** [comment]
It's worked for me. I can logged in after pull your reverted.

**Comment by ChristianGiupponi** [comment]
Not working for me on a fresh install.  I have just clone the project, run composer install but can''t login

**Comment by ChristianGiupponi** [comment]
I can confirm that now it works

**Pull request closed without merging**
