### PR TITLE
Vuejs component: Multiple file selector

### PR DESCRIPTION
**Pull request by daothanh**
Here to include component to your view:

1. `Import MultipleFileSelector from '../../../../Media/Assets/js/mixins/MultipleFileSelector';`
2. Add `MultipleFileSelector` into your `mixins` array
3. Add component in your view (replace Post and post by your entity):
`<multiple-media ref="multiple-media" zone="gallery" @fileUnselected="unselectFile($event, 'post')"
                                                @multipleFileSelected="selectMultipleFile($event, 'post')"
                                                entity="Modules\Post\Entities\Post"
                                                :entity-id="$route.params.post"
                                                :label="trans('posts.form.gallery')"></multiple-media>`

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

Sorry, I haven't had the time to test your PR yet, but haven't forgotten it. 😄

**Comment by motchju** [comment]
will be so nice to have it validated

**Comment by nWidart** [comment]
actually this doesn't look like it can be merged. There are a lof of changes unrelated to the feature.

**Comment by nWidart** [comment]
@daothanh Is it possible to make a PR with jus the feature?

**Pull request closed without merging**
