### PR TITLE
Add view type media-single on Setting Module

### PR DESCRIPTION
**Pull request by darron1217**
I added view type media-single on Setting Module
to resolve logo uploading issue #474

### CODE REVIEW

**Comment by bloggervista** [comment]
nice PR :)

**Comment by bloggervista** [comment]
if if it don't get merged i guess you can published it :)

**Comment by nWidart** [comment]
Looks good, but tests are failing 😄

**Comment by darron1217** [comment]
Can anybody help me to fix test errors?
I have no idea how to solve it..

**Comment by darron1217** [comment]
I've added the codes below to BaseTestCase.php but still not working
```
        $this->artisan('migrate', [
            '--database' => 'sqlite',
            '--path'     => 'Modules/Media/Database/Migrations',
        ]);
```

**Pull request closed without merging**
