### PR TITLE
Locale Repository

### PR DESCRIPTION
**Pull request by xfudox**
Recently I had the need to handle locales as data to be saved along models (e.g.: a list of spoken languages), so I made a simple vue remote select component with its own api endpoint, request, controller and repository.

### CODE REVIEW

**Comment by nWidart** [comment]
Hi,
Thank you for your contribution! This looks good. I'm wondering what the form request is for, it doesn't look like it can persist something?

**Comment by xfudox** [comment]
I've been busy these day, so as soon as i can i'll fix the branch to pass the tests.

To answer your question i created a custom request just to validate the data sent to the LocaleRepository, probably extending it from the FormRequest is not necessary, but i can't understand what you mean when you say about the possibility to have it persist something, maybe i'm missing something from the whole picture.

**Comment by xfudox** [comment]
Ok, i gave a look to the integretion tests errors: it is a test from the Asgard Media module, MaxFolderSizeRuleTest::it_validates_max_folder_size_is_valid

How can this test fail? my merge didn't affect (I think/hope) anything related to this.
Maybe i'm missing something.

**Comment by nWidart** [comment]
Hello,

You can ignore that test yeah, I need to disable it.

By persisting I mean writing on disk.
That's why I assumed when I saw a form request. What data is sent to the repository that needs to be validated?

**Comment by xfudox** [comment]
I made a request just to validate the data for the research, not to validate data to be saved.

I consider the api endpoint used by the vue component an "unsafe entrypoint", so i made along it a related request to validate the data given for the research and ensure my eloquent repository logic receive correct data to work on.

**Comment by xfudox** [comment]
Bumping this up

Any news?

**Comment by nWidart** [comment]
Thanks for the bump, sorry 🤗

Looks good, thank you! 👍

**Comment by xfudox** [comment]
Thanks @nWidart  👍

**Pull request merged**
