### PR TITLE
Change status label and checkbox and make it much more understandable

### PR DESCRIPTION
**Pull request by ChristianGiupponi**
schermata 2019-02-13 alle 10 49 02

### CODE REVIEW

**Comment by mikemand** [comment]
What does it look like enabled?

**Comment by ChristianGiupponi** [comment]
Same but green
schermata 2019-02-14 alle 09 03 27

**Comment by nWidart** [comment]
Could this be pointed to master?

**Comment by ChristianGiupponi** [comment]
Sorry, I just missed this comment. I will do ASAP

**Pull request closed without merging**
