### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by matijakovacevic**
Ignore Dolphin File Manager .directory file (for directory settings on Linux)

### CODE REVIEW

**Comment by mikemand** [comment]
This would be something to put in your personal global `.gitignore`, like IDE config files (e.g.: PhpStorm's `.idea` directory).

**Comment by nWidart** [comment]
Thanks for the contribution.

I agree with @mikemand , this is something that should be in your global gitignore file. 👍

**Comment by matijakovacevic** [comment]
Didn't know about global .gitignore.
I agree.

Learned something today 👍 thanks :)

**Comment by nWidart** [comment]
Indeed, that's where we put stuff depending on local setup, like for instance the .idea folder for phpstorm, .DS_STORE on macs etc.

**Pull request closed without merging**
