### PR TITLE
Fix creating a new user. Closes #496.

### LINKED ISSUE #496: Cannot generate API key for newly created user
Api key generation throws error, so I can't use media library with a new user. Actually it does not throw any error - just an empty response with error code 500.

### Steps to reproduce
Create a user from the admin panel.
Log in with the new user and try to generate API key.

### System Details
- OS
Windows 10 x64
- PHP Version
7.1
- Laravel Version
5.5
- `Asgardcms/Platform` version
3.5.2

### PR DESCRIPTION
**Pull request by Fisiu**
Create user's token for newly created user.
Fix for setting a new acount as already activated.

Signed-off-by: Mariusz Fik <mariusz@fidano.pl>

### CODE REVIEW

**Comment by nWidart** [comment]
Thank you for the contribution!

Could you create a test to make sure this token is indeed created please?

Thanks!

**Comment by Fisiu** [comment]
Further investigation showed, that wrong/broken smtp configuration causing issue with token.
I'll update PR to include fix only for creating already activated account. 
```php
[2018-05-06 02:43:44] local.ERROR: Connection could not be established with host mailtrap.io [Connection timed out #110] {"userId":1,"email":"mariusz@fidano.pl","exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host mailtrap.io [Connection timed out #110] at /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269)
[stacktrace]
#0 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->establishSocketConnection()
#1 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(126): Swift_Transport_StreamBuffer->initialize(Array)
#2 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(67): Swift_Transport_AbstractSmtpTransport->start()
#3 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send('user::emails.we...', Array, Object(Closure))
#6 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(52): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#7 [internal function]: Illuminate\\Mail\\SendQueuedMailable->handle(Object(Illuminate\\Mail\\Mailer))
#8 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#13 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Mail\\SendQueuedMailable))
#14 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Mail\\SendQueuedMailable))
#15 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Mail\\SendQueuedMailable), false)
#17 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#18 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
#19 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(148): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Mail\\SendQueuedMailable), '', NULL)
#20 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(58): Illuminate\\Queue\\SyncQueue->later(NULL, Object(Illuminate\\Mail\\SendQueuedMailable), '', NULL)
#21 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(163): Illuminate\\Queue\\Queue->laterOn(NULL, NULL, Object(Illuminate\\Mail\\SendQueuedMailable))
#22 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(137): Illuminate\\Mail\\Mailable->later(NULL, Object(Illuminate\\Queue\\QueueManager))
#23 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(357): Illuminate\\Mail\\Mailable->queue(Object(Illuminate\\Queue\\QueueManager))
#24 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(127): Illuminate\\Mail\\Mailer->queue(Object(Modules\\User\\Emails\\WelcomeEmail))
#25 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(96): Illuminate\\Mail\\PendingMail->queue(Object(Modules\\User\\Emails\\WelcomeEmail))
#26 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/User/Events/Handlers/SendRegistrationConfirmationEmail.php(33): Illuminate\\Mail\\PendingMail->send(Object(Modules\\User\\Emails\\WelcomeEmail))
#27 [internal function]: Modules\\User\\Events\\Handlers\\SendRegistrationConfirmationEmail->handle(Object(Modules\\User\\Events\\UserHasRegistered))
#28 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(369): call_user_func_array(Array, Array)
#29 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Modules\\\\User\\\\Ev...', Array)
#30 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(465): Illuminate\\Events\\Dispatcher->dispatch('Modules\\\\User\\\\Ev...')
#31 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/User/Repositories/Sentinel/SentinelUserRepository.php(63): event(Object(Modules\\User\\Events\\UserHasRegistered))
#32 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/User/Repositories/Sentinel/SentinelUserRepository.php(79): Modules\\User\\Repositories\\Sentinel\\SentinelUserRepository->create(Array, NULL)
#33 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/User/Http/Controllers/Api/UserController.php(53): Modules\\User\\Repositories\\Sentinel\\SentinelUserRepository->createWithRoles(Array, Array, NULL)
#34 [internal function]: Modules\\User\\Http\\Controllers\\Api\\UserController->store(Object(Modules\\User\\Http\\Requests\\CreateUserRequest))
#35 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#36 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#37 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Modules\\User\\Http\\Controllers\\Api\\UserController), 'store')
#38 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#39 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#40 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/User/Http/Middleware/TokenCan.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Modules\\User\\Http\\Middleware\\TokenCan->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'user.users.crea...')
#43 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/Core/Http/Middleware/AdminMiddleware.php(71): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Modules\\Core\\Http\\Middleware\\AdminMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/Modules/User/Http/Middleware/AuthorisedApiToken.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Modules\\User\\Http\\Middleware\\AuthorisedApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#55 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#59 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#60 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#61 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#62 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#82 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#83 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#84 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#85 /home/fisiu/Devel/PHP/Work/mania-w-edukacji/server.php(21): require_once('/home/fisiu/Dev...')
#86 {main}
```

**Comment by nWidart** [comment]
Ah I think that's because mailtrap changed its hostname. I think it's now `smtp.mailtrap.io`.

**Comment by nWidart** [comment]
I just realised with your test that you create a token in the controller. This should probably happen in the user repository. 
The Web is an implementation detail, so if something else tries to do the same they will also have to think about the token issue.
Whereas if it's in the repository, they just need to call the repository.

**Pull request closed without merging**
