### PR TITLE
Add canonical and Alternate link

### PR DESCRIPTION
**Pull request by ChristianGiupponi**
This commit add canonical and alternate links for pages in each language.
Sorry for the first 2 commit, it was a mistake, the second just revert the first, the 3rd is correct

### CODE REVIEW

**Comment by nWidart** [comment]
Hello & thank you for the contribution!

I'm not seeing where you send the data to the view.

**Comment by ChristianGiupponi** [comment]
Hi @nWidart you're right, I did a mess with this pull request, I have send another with the fix.  
I'm exploring the cms to send more updates

**Comment by ChristianGiupponi** [comment]
@nWidart did you see the update?

**Comment by nWidart** [comment]
Sorry for the late reply. 

Thank you!

**Pull request merged**
