### PR TITLE
fix route:cache and config:cache issue

### PR DESCRIPTION
**Pull request by huydang284**
Hi @nWidart,

Please review my solution to fix route:cache issue.
If my solution is accepted, you can merge it to branch 3.0 also.

Regards,
Huy Dang

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

It looks like the tests are failing.

**Comment by nWidart** [comment]
I'm guessing because of the `setting('core::locales')` call which makes a database call.

**Comment by huydang284** [comment]
Yes you are right @nWidart. 
I made a manual testing in my local site and it worked well ok so I think we should update test code.

**Comment by huydang284** [comment]
Hi @nWidart,

I have fixed config:cache issue also.
We should set `INSTALLED` in config file because when we cache configs, we cannot use `env` function (You can see it in `laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php:21`)

Please review and you can merge my fix to branch 3.0 also.

**Comment by huydang284** [comment]
I have not known about Docker, so can you update docker and configuration to test my commit?

**Comment by huydang284** [comment]
Hi @nWidart,
I have just updated my code for passing tests.
Please review my code 😁

**Comment by huydang284** [comment]
Hi @nWidart,

It is needed because when we cache route via `php artisan route:cache`:
- `bootstrap/cache/routes.php` will be created, it contain routes but it does not have routes with locale prefix.
- when `bootstrap/cache/routes.php` exsits, application will read this file to get routes instead of go to each route file.

=> So when we access `http://example.com/en`, application will not find suitable route.

**Comment by huydang284** [comment]
Hi @nWidart,
I created another pull request on version 3 here: https://github.com/AsgardCms/Platform/pull/554
Please merge this pull request also, I think many people will use version 2.

Thank you,
Huy Dang

**Comment by nWidart** [comment]
Thanks 👍

**Pull request merged**
