### PR TITLE
Add additional install script to prompt for APP_URL

### PR DESCRIPTION
**Pull request by johnsvenn**
Add additional install script to prompt for APP_URL when gathering information to create the .env file

Give users the opportunity to set the APP_URL to something other than localhost, lots (most?) people run multiple sites in their local development servers.

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks!

**Comment by johnsvenn** [comment]
Thanks.

Do you think it would be useful the same for the other variables like
Cache, Redis, Mail? If so I would be happy to create installer scripts for
those too.

I'm not sure if it would be beneficial - do people set those variables
often enough when starting projects for it to be worth the additional
questions (even if you do just have to press return to accept the
defaults)? I suppose you could simply have a single option something like:
Would you like to configure Cache, Redis, and Mail settings? yes/no
(default no)

**Comment by joshbrw** [comment]
My own personal opinion on this is that the installer shouldn't become too bloated with setting environment variables interactively. It's true that one of the nicer features of Wordpress is the interactive installation process, but it's worth remembering that AsgardCMS is aimed at a slightly different audience - an audience that is likely familiar enough with Laravel to do this manually.

**Comment by nWidart** [comment]
I agree with @joshbrw 

I don't think it's needed to ask too much during install. Especially since during development, not all are needed right at the start of a project.

An additional script that could be helpful however is one that runs `npm run dev` to compile vuejs related assets.
An issue with this is that it requires npm to be installed locally for instance.

**Pull request merged**
