### PR TITLE
Fix for Issue #455 (Adding support for UTF-8 slug)

### PR DESCRIPTION
**Pull request by darron1217**
Fix for Issue #455 (Adding support for UTF-8 slug)

### CODE REVIEW

**Comment by nWidart** [comment]
Looks like the tests fail b/c the file isn't required in the tests.

I'm also thinking maybe this is something that should be sent to laravel instead?

**Comment by darron1217** [comment]
@nWidart 
Laravel rejected similar PR... :(
They recommend implementing `utf8 slug` method by ourselves

https://github.com/laravel/framework/pull/6867

**Comment by nWidart** [comment]
Hello,

Could you add a test for this method?

**Comment by nWidart** [comment]
Thanks, maybe it's also worth pulling in all the tests `str_slug()` has on its own?

**Comment by darron1217** [comment]
@nWidart Okay

Is this code below is what you said?

https://github.com/laravel/framework/blob/9cf82b9fa7edf5a66a78e69c91abb685f13ed4a1/tests/Support/SupportStrTest.php#L138-L145

**Comment by nWidart** [comment]
That looks like it indeed. Since we're replicating that method just to make sure the 'base' cases work, and keep working in the future 😄 

Maybe have one test with all the new ones, plus your new one added.

**Comment by darron1217** [comment]
@nWidart I've done it :)

**Comment by nWidart** [comment]
Thanks! 👍

**Pull request merged**
