### PR TITLE
Add "Update and Back" button to User edit

### PR DESCRIPTION
**Pull request by mikemand**
Allows developer to let users edit their own profile without having an error upon saving because they cannot list all users.

### CODE REVIEW

**Comment by mikemand** [comment]
The alternative to this is to create an actual "Profile" page that is outside of the main `user.*` permissions so users that don't have `user.users.index` (and/or `user.users.edit`) permissions can still edit their profile.

**Comment by armababy** [comment]
+1 for seperating users list to personal profile.

**Comment by mikemand** [comment]
Would you do just an edit, or a view as well?

**Comment by armababy** [comment]
I think it would be very neat to make profile viewable and editable by owning user, that does not require users permissions.
When working with more that 1-2 people in same CMS some of the groups would not be able to view users and their details, but should view and edit their own profile.

Maybe good start could be just edit view. If we look in AdminLTE there's perfect place for linking to profile in right top hand corner in dropdown.

**Comment by mikemand** [comment]
Yeah, I have a button there now (at the top right dropdown). I also put it in the sidebar under the "My Account" heading.

I will start with just an edit profile page then, and if someone needs a "View Profile" page, they can PR it later on

**Comment by nWidart** [comment]
I like the user profile idea as well, though in another PR :)

I'll already merge this is as this is a good idea either way.

**Pull request merged**
