### PR TITLE
Added boolean `$checked` param to `Form::macro('i18n/normalCheckbox')`

### PR DESCRIPTION
**Pull request by arturmamedov**
Added boolean `$checked` param to `Form::macro('i18n/normalCheckbox')` for add the default checked state.

### CODE REVIEW

**Comment by arturmamedov** [comment]
I initially try with a `$array_options = []` but it was a overdo https://gist.github.com/arturmamedov/a3e87eda1dc9fa1a8a666c9184ce6b0d

**Comment by arturmamedov** [comment]
Why?

**Comment by nWidart** [comment]
Because I don't see the need for it, this can already be done.

**Comment by arturmamedov** [comment]
@nWidart ah i didn't know, can you explain me how please! Thank Nicolas!

**Comment by nWidart** [comment]
You can see the form macro for that.

```
if (is_object($object)) {
        $currentData = isset($object->$name) && (bool)$object->$name ? 'checked' : '';
    } else {
        $currentData = false;
    }

    $oldInput = old($name, $currentData) ? 'checked' : '';
```

**Comment by mikemand** [comment]
What I like to do is make a new entity in my controller and pass it to my view, so I can use the same form fields for create and update (unless there is something drastically different I need for one or the other, but this is rare).

For example:

```php
/**
 * Show the form for creating a new resource.
 *
 * @return Response
 */
public function create()
{
    $recipe = new Recipe();

    return view('recipe::admin.recipes.create', compact('recipe'));
}
```

This way, you can initialize your form with default data, just by adding it to the entity:

```php
$recipe = new Recipe([
    'active' => true',
    'something' => 'This is something',
    etc...
]);
```

**Comment by arturmamedov** [comment]
@mikemand Thank you man! Your way is very nice and clean!

**Pull request closed without merging**
