### PR TITLE
App/Laravel - Dimsav/Translatable become Astrotomic/Translatable

### PR DESCRIPTION
**Pull request by arturmamedov**
composer updated and replaced all namespaces and usage

### CODE REVIEW

**Comment by nWidart** [comment]
Hi,

Thanks for the contribution! I'll add the hacktoberfest tag so it counts for you :) 
It looks like the tests fail because it can't find the class, probably a orchestra fix to do.

**Comment by arturmamedov** [comment]
Thank for hacktoberfest tag.

I think it can't find the class cause it get `idavoll/core-module` that haven't the `astrotomic` dependincy

**Comment by imagina** [comment]
@nWidart , travis is failing because you need to update the composer.json in the Core Module.

**Comment by nWidart** [comment]
That's something that should be changed here in this PR.

**Comment by imagina** [comment]
> That's something that should be changed here in this PR.

It is, 

image

but travis is executing a composer update and overwriting the core module with the one at the repo :

image

**Comment by nWidart** [comment]
Oh I see my bad, I missed that. In that case it'll fixes itself after the merge 👍 
Thanks!

**Comment by nWidart** [comment]
Looks like they're still failing: https://travis-ci.org/github/AsgardCms/Platform/jobs/734088235

**Comment by mikemand** [comment]
I thought I'd take a crack at fixing this, but...

`config:publish` isn't even a command, and when I use `vendor:publish` to publish Translatable's config file, it isn't recognizing it. I'm not quite sure what could be wrong, but I'm going to try clearing a few more things out before testing a bare Laravel install to see if it is their package or something we aren't doing.

**Comment by mikemand** [comment]
Ok, so I am super confused. The Menu test error is just weird. It creates the pages just fine (I've stepped through the output of the Page repository's `create` method line by line to see what it is doing during the test when creating pages), but when the Menu goes to get built it won't pull the translations from the page. I don't understand why. The Page has translations here: https://github.com/AsgardCms/Platform/blob/604a22cce9ae1cf920300c8eca84018b3b297455/Modules/Menu/Tests/MenuItemUriGeneratorTest.php#L56-L64 (assign the output of `$this->page->create` to a variable and dump it to check). When the menu uri is generated, it pulls a fresh copy of the page - but it doesn't have translations for some reason.

@nWidart: Maybe we should just pass the Page object to the `MenuItemUriGenerator`? That would prevent us from having to load a fresh copy of the page within the generator, which is a good thing in my opinion, but I know you have a specific methodology/pattern to how you set up the code initially. This would probably break some rule of that coding pattern. 😄

**Comment by nWidart** [comment]
Hm very strange, worth a try but seems strange. I see that service is querying the database.

**Comment by mikemand** [comment]
So passing the page didn't solve the issue, since it is failing when querying for the "parent" page. Back to the drawing board, as they say.

**Comment by arturmamedov** [comment]
Sorry i haven't time to check, want to do this today, the problem is that test fail after this change?

**Comment by nWidart** [comment]
the issue has been fixed here: https://github.com/AsgardCms/Platform/pull/782 by @imagina I believe.

**Pull request merged**
