### PR TITLE
Remove explicit registration of debugbar

### LINKED ISSUE #599: Remove > Illuminate\Foundation\ComposerScripts::postAutoloadDump  from pakacge
### Summary of issue
I'm trying to install your project without the dev files and get the following

> Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
>  @php artisan package:discover
> In Application.php line 635:
>   Class '\Barryvdh\Debugbar\ServiceProvider' not found
> Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

perhaps we can remove this from the default 

### Steps to reproduce

1) run `composer create-project asgardcms/platform src --prefer-dist --no-dev`

### System Details

- Operating System = Vagrant Ubuntu
- PHP Version  7.0
- Laravel Version - 5.4.
- `Asgardcms/Platform` version - 3.6.1

### PR DESCRIPTION
**Pull request by mikemand**
Fixes #599

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks! changing the target to master

**Comment by mikemand** [comment]
I would have targeted Master, but could not since #598 wasn't merged. 😛

**Comment by nWidart** [comment]
haha yea I saw I had to merge that before :D

**Comment by arturmamedov** [comment]
> 
> 
> See: #599

Thank u!

**Pull request merged**
