### PR TITLE
Added Image Attribute

### PR DESCRIPTION
**Pull request by chiragpipariya**
Due to this function images can show in frontend and admin both.

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks for the contribution. 👍

**Comment by chiragpipariya** [comment]
Have push this code in master branch ?

**Comment by nWidart** [comment]
3.0 is the correct branch. It's not released yet.

**Comment by chiragpipariya** [comment]
when you release it ?

**Comment by chiragpipariya** [comment]
ohh great, 
no problem. take your time.

**Comment by nWidart** [comment]
It was just released as version [3.6.0](https://github.com/AsgardCms/Platform/releases/tag/3.6.0)

**Comment by chiragpipariya** [comment]
Thanks a lot.

**Pull request merged**
