### PR TITLE
Check page status if page exists.

### PR DESCRIPTION
**Pull request by Fisiu**
Signed-off-by: Mariusz Fik <mariusz@fidano.pl>

### CODE REVIEW

**Comment by nWidart** [comment]
Why is this needed?

**Comment by Fisiu** [comment]
I page is not found we should return 404, no need to check it's staus. We should check status only if page exists.

**Comment by nWidart** [comment]
This was already done, you just split it in 2 ifs, so why? :D 
A better solution might be to inverse the condition order.

```php
is_null($page) || $page->status == 0
```

**Comment by huydang284** [comment]
I agree with @nWidart.

It should be `is_null($page) || $page->status == 0`

**Comment by Fisiu** [comment]
It took me a while to get back to work on asgardcms. Here is expected implementation.

**Comment by nWidart** [comment]
Thanks!

**Pull request merged**
