### PR TITLE
Updating typicms/nestablecollection package

### PR DESCRIPTION
**Pull request by darron1217**
Solving issue #485

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

Have you tested that this works? 
I remember having to use that specific version in order to have it working.

**Comment by darron1217** [comment]
@nWidart 
I think there's no breaking-changes between release 1.1.1 and master branch.
Take a look at it :)
https://github.com/TypiCMS/NestableCollection/compare/e75ed5efaf7cf8d98a44fd31e0435352a3bae0ff...master

**Comment by darron1217** [comment]
I've also tested it working well with menu-module :)

**Comment by nWidart** [comment]
Thanks!

**Pull request merged**
