### PR TITLE
There Should be "is_activated"

### PR DESCRIPTION
**Pull request by chiragpipariya**
There Should be "is_activated" instead of activated 
while doing update of create user there is error in ajax calling. 
please correct it. 

thanks

 
image

### CODE REVIEW

**Comment by mikemand** [comment]
Looks like the tests need to be fixed too:

https://github.com/AsgardCms/Platform/blob/e43253627a55601e5e86b5372d6d2e40bc368b57/Modules/User/Tests/SentinelUserRepositoryTest.php#L302
https://github.com/AsgardCms/Platform/blob/e43253627a55601e5e86b5372d6d2e40bc368b57/Modules/User/Tests/SentinelUserRepositoryTest.php#L322
https://github.com/AsgardCms/Platform/blob/e43253627a55601e5e86b5372d6d2e40bc368b57/Modules/User/Tests/SentinelUserRepositoryTest.php#L345

**Comment by mikemand** [comment]
This should fix #583

**Comment by chiragpipariya** [comment]
@mikemand i changed there also, once @nWidart accept it'll works.

**Comment by motchju** [comment]
Hello, thanks for the fix @mikemand hopefully it will be merged soon

**Comment by nWidart** [comment]
Where is the fix? I see the tests still failing on this PR.

**Pull request closed without merging**
