### PR TITLE
Role Slug Unique Validation Fix

### PR DESCRIPTION
**Pull request by moebrowne**
The unique validation for role slugs was not ignoring the current role preventing roles from being updated

### CODE REVIEW

**Comment by nWidart** [comment]
Does this still work for create?

**Comment by moebrowne** [comment]
Indeed, on create duplicate slugs are rejected and unique ones are accepted

**Comment by nWidart** [comment]
Hm strange, I'll test it out since it could be an object.

**Comment by moebrowne** [comment]
I thought that `roles` was going to be an object but it doesn't look like roles have a route binding

**Pull request merged**
