### PR TITLE
Fix BindingResolutionException

### PR DESCRIPTION
**Pull request by vs7**
Unresolvable dependency resolving [Parameter #1 [ &lt;required&gt; $name ]] in class Nwidart\Modules\Module

### CODE REVIEW

**Comment by mikemand** [comment]
A better solution would be to add the `'bindings',` middleware to the API config [here](https://github.com/AsgardCms/Platform/blob/2.0/Modules/Core/Config/core.php#L59-L60).

**Comment by vs7** [comment]
Hi! Show please.

**Comment by mikemand** [comment]
Hello @vs7,

In your `/config/asgard/core/core.php` add `'bindings',` to the `api` array in the `middleware` section:

```php
'middleware' => [
    ...
    'api' => [
        'bindings',
    ],
],
```

**Comment by vs7** [comment]
It doesn't help

**Comment by mikemand** [comment]
Hmm.

You are trying to publish the module's assets from `http://yoursite.com/backend/workshop/modules/<module>`, correct? When I try that, I end up with a 401 Unauthorized. LOL

**Comment by mikemand** [comment]
@vs7, I am able to successfully solve your problem with the following in my `/config/asgard/core/core.php`, starting at line 45 (for the comment, 53 for the actual array):

```php
    /*
    |--------------------------------------------------------------------------
    | Middleware
    |--------------------------------------------------------------------------
    | You can customise the Middleware that should be loaded.
    | The localizationRedirect middleware is automatically loaded for both
    | Backend and Frontend routes.
    */
    'middleware' => [
       'backend' => [
           'auth.admin',
       ],
       'frontend' => [
       ],
       'api' => [
           'bindings',
       ],
    ],
```

**Comment by vs7** [comment]
Yes, i'm trying to publich module's assets. But unfortunately the line in config doesn't help.

**Comment by mikemand** [comment]
Can you tell me your versions of Asgard, Laravel, and PHP please? I can replicate the error if I remove the `bindings` middleware, but adding the middleware solves it for me.

Also, can you confirm that you have a `bindings` key in the `$routeMiddleware` array in `/app/Http/Kernel.php`, like so:

```php
    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        // 'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
```

**Comment by vs7** [comment]
I suppose 'bindings' should be enabled by default for api routes.

**Comment by mikemand** [comment]
Hi @vs7,

Yes, that's what I'm trying to have you do. It is not currently enabled for API routes (and I don't think Laravel enables them by default either).

**Comment by vs7** [comment]
I understand. But I think it should be enabled out of the box in AsgardCMS.
Not in config.

**Comment by mikemand** [comment]
Oh, I see what you mean now. Yes, I think it should be as well. I want to hear what @nWidart says about that, though.

**Comment by vs7** [comment]
Maybe you can propose a patch?

**Pull request closed without merging**
