### PR TITLE
New helper for dynamically generating datatables for cleaner views.

### PR DESCRIPTION
**Pull request by irmakh**
I'm using this helper function to clean some of my views by auto generating data tables using an array. might be useful.

### CODE REVIEW

**Comment by joshbrw** [comment]
This could really do with going into a specific class for generating data-tables. Too much code for a helper method.

**Comment by nWidart** [comment]
I agree. I think using laravel new Components would be good use-case for this.

**Comment by irmakh** [comment]
What about creating a view for HTML and just returning it inside helper method?

**Comment by nWidart** [comment]
Hm better, but components fits the use-case perfectly actually.

**Comment by irmakh** [comment]
Got it! Thanks for opinions. Cheers.

**Comment by nWidart** [comment]
Thanks for the contribution though! I can see this being useful 👍

**Comment by mikemand** [comment]
This also needs to have the ability to generate a footer too.

**Pull request closed without merging**
