### PR TITLE
By default add the 1.0.0 version to all modules generated with asgard:module:scaffold

### PR DESCRIPTION
**Pull request by ChristianGiupponi**

### CODE REVIEW

**Comment by nWidart** [comment]
Hello, thank you for the contribution.
Could you add a test for this please?

**Comment by ChristianGiupponi** [comment]
Hi @nWidart I have added the test

**Comment by nWidart** [comment]
Thank you! 👍

**Comment by ChristianGiupponi** [comment]
I have added the theme version and test as well

**Comment by nWidart** [comment]
Thanks!

**Pull request merged**
