### PR TITLE
Fix: add COMPOSER_MEMORY_LIMIT env variable to fix Memory Issues in T…

### PR DESCRIPTION
**Pull request by imagina**
…ravis CI.

### CODE REVIEW

**Comment by nWidart** [comment]
Thank you very nice!
I'm surprised it only works on PHP 7.1 🤔

**Comment by mikemand** [comment]
It's working for the other PHP versions too, but it looks like Travis had database issues:

> 1) Modules\Menu\Tests\EloquentMenuItemRepositoryTest::it_should_create_menu_item_as_root
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such index: IDX_EA23F583EE35BD72 (SQL: DROP INDEX IDX_EA23F583EE35BD72)

**Comment by imagina** [comment]
@mikemand  @nWidart I was digging in the issue and it's not Travis

Seems to be related to SQLite and PDO now failing some previously "silent" errors. Like Drop Foreign Keys and Dropping Indexes.

https://github.com/laravel/framework/issues/25475

**Comment by imagina** [comment]
Ok, i found the issue. It's caused by a regression in doctrine/dbal. Downgrading to 2.10.2 fixes the problem at least in my test with PHP 7.2

Soon to be fixed on  doctrine/dbal 2.10.4   https://github.com/doctrine/dbal/issues/4243

I'll send a pull request to force the doctrine/dbal version to the last one working:  2.10.2

**Comment by imagina** [comment]
PR sent: https://github.com/AsgardCms/Platform/pull/768

**Pull request merged**
