### PR TITLE
load factories

### PR DESCRIPTION
**Pull request by xfudox**
Updated service provider stub to load module factories

### CODE REVIEW

**Comment by xfudox** [comment]
sorry, made a branch including commits for the other pull request

**Comment by mikemand** [comment]
You can rebase your branch on `master` to fix the extra commits from your other PR.

**Comment by nWidart** [comment]
Indeed as Mike said since your last PR was merged you can do that now.

**Comment by xfudox** [comment]
Since i made the other pr from master (my fault) rebasing this branch on master will not work, so i'm gonna close this pull request and open a new clean one

**Pull request closed without merging**
