### PR TITLE
Implement pagination on Media-Grid popup

### PR DESCRIPTION
**Pull request by darron1217**
Solve issue #557

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks.

Does this handle pagination with the page selection on the grid? Ie, it'll make the correct request to the correct location?

If I remember correctly it required more than this in order to perform server-side pagination.

**Comment by darron1217** [comment]
image

Actually, I didn't implemented search option
But it works well :)

**Comment by darron1217** [comment]
I'm not doing ajax pagination

It's just workaround to implement the function on media-grid

**Comment by nWidart** [comment]
I'm not sure what this fixes then

**Comment by darron1217** [comment]
This will improve performance a lot

In my case, I reduced delay from 30 sec to 1 sec

**Comment by darron1217** [comment]
Sorry but I'll change my opinion that it is workaround

It's not workaround. It really solves problem

**Comment by nWidart** [comment]
To me, this can't work if you don't handle pagination and search.

When changing pages, it needs to load the content of the next page, via an http request.

**Comment by darron1217** [comment]
This page (the media-grid popup) didn't have search functionality before...

And this PR contains pagination functionality already
What do you mean that "don't handle pagination"?

**Comment by darron1217** [comment]
I posted captured image of this pagination functionality already

**Comment by nWidart** [comment]
It did have search before, provided by datatables.

I don't see any pagination functionality.

**Comment by nWidart** [comment]
So tell me where do you make a http request on page change? Where do you make one on search?

**Comment by darron1217** [comment]
Oh I see... I missed that point. Yes, it had search function before

**Comment by darron1217** [comment]
Changing page is not implemented on javascript way, but native browser way.

The link has changed by adding '?page=2' on captured image

**Comment by nWidart** [comment]
Oh I see ok, that makes sense.

With this however the search will only search the results on the current page.

**Comment by nWidart** [comment]
I'll close this for now as I think it might be better to implement it fully with server-side pagination.

**Pull request closed without merging**
