### PR TITLE
Update to Laravel v8.13.0

### PR DESCRIPTION
**Pull request by imagina**

### CODE REVIEW

**Comment by nWidart** [comment]
Some conflicts since the laravel 7 PR merge, but looks good! 👌

**Comment by mikemand** [comment]
Ziggy v1 was released recently. As far as I can tell, there will be no breaking changes for us.

**Comment by mikemand** [comment]
Also, `yajra/laravel-datatables-oracle` needs to be bumped to `^9.0`. Seems to only be in the Core module.

**Comment by nWidart** [comment]
I'll be able to merge this once the conflicts have been resolved.

**Comment by imagina** [comment]
@nWidart , Can you update nwidart/laravel-menus to be compatible with Laravel 8.x.  The module is working fine. You should only update the composer.json to make it available for install.

**Comment by nWidart** [comment]
Done: https://github.com/nWidart/laravel-menus/releases/tag/7.0

**Comment by imagina** [comment]
Thank you @nWidart , updated!

**Comment by nWidart** [comment]
Thanks!

**Pull request merged**
